# This is the computation for the physical deformation of electrode
# compliant electroactive polymer of specified material properties

# Think about using PVDF or Kynar film from Arkema (US) ro Porex (US)

# Use a terpolymer variation of PVDF, RT dielectric ~50, exhibits
# electrostriction effects where there is substantial deformation orthogonal
# to the applied electric field. NOTE: wiki electrostriction. NOTE: application
# of recerse electric field does not induce reversed deformation???

import math

# applied_V is the applied voltage to the electrodes
applied_V = float(input("Input the applied voltage in volts: "))

# separation_d is the thickness of the dielectric material
separation_d = float(input("Input the separation distance in units of mm: "))

# er is the material dielectric constant
er = float(input("Input the material dielectric constant in non-units: "))

# eo is the absolute dielectric permittivity
eo = 8.854187817*math.pow(10,-12)

# P_elec is the electric pressure generated by the applied voltage to the
# dielectric material
P_elec = 0.5*eo*er*(math.pow(applied_V,2)/(math.pow(separation_d,2)))

print("Electrical pressure: " + str(P_elec) + " MPa")

youngs_mod = input("Input Young's Modulus in units of MPa: ")





P_mech = 2*P_elec
